apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: narmesteleder-varsel
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: narmesteleder-varsel-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: narmesteleder-varsel
            envVarPrefix: NAIS_DATABASE
        tier: db-f1-micro
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 120m
      memory: 512Mi
  envFrom:
    - secret: narmesteleder-varsel-secret
  kafka:
    pool: nav-dev
  env:
    - name: KAFKA_CLIENT_ID
      value: narmesteleder-varsel
